# Generated by Django 4.2.20 on 2025-03-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group_follow_post_group_follow_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
